/**
 * MASTER CATALOG OF SG-SST INDICATOR DEFINITIONS
 * PROMPT 37 SPECIFICATION (Section 2, 5-33, 38)
 */

import { IndicatorDefinition } from './types';

export const MASTER_INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  // =========================================================================
  // 1. ANTROPOMETRÍA
  // =========================================================================
  {
    id: 'ind_imc_promedio',
    code: 'ANTROP-01',
    name: 'Índice de Masa Corporal Promedio (IMC)',
    description: 'Promedio del Índice de Masa Corporal evaluado exclusivamente sobre colaboradores con peso y estatura válidos de forma simultánea.',
    category: 'ANTROPOMETRIA',
    formula: 'SUM(pesoKg / (estaturaMts^2)) / COUNT(colaboradores con peso y estatura válidos)',
    unit: 'kg/m²',
    numerator: 'Suma de los IMC individuales calculados',
    denominator: 'Total de colaboradores con registro válido y simultáneo de peso y estatura (excluye registros con algún dato faltante o inválido)',
    requiredFields: ['pesoKg', 'estaturaMts'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { min: 18.5, max: 24.9, label: 'Normopeso' },
      yellow: { min: 25.0, max: 29.9, label: 'Sobrepeso' },
      red: { min: 30.0, label: 'Obesidad' }
    },
    notes: 'No utiliza el total de colaboradores censados si no cuentan con antropometría completa.'
  },
  {
    id: 'ind_imc_clasificacion',
    code: 'ANTROP-02',
    name: 'Distribución por Clasificación Nutricional (IMC)',
    description: 'Proporción de colaboradores según los 6 rangos de clasificación nutricional de la OMS (Bajo peso, Normal, Sobrepeso, Obesidad I, Obesidad II, Obesidad III).',
    category: 'ANTROPOMETRIA',
    formula: 'COUNT(colaboradores en rango IMC) / COUNT(colaboradores con IMC válido) * 100',
    unit: '%',
    numerator: 'Conteo de colaboradores en cada categoría nutricional',
    denominator: 'Total de colaboradores con IMC calculable',
    requiredFields: ['pesoKg', 'estaturaMts'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { min: 60, label: 'Mayoría en peso saludable' },
      yellow: { min: 40, max: 59.9, label: 'Prevalencia moderada de sobrepeso/obesidad' },
      red: { max: 39.9, label: 'Alta prevalencia de malnutrición/obesidad' }
    }
  },
  {
    id: 'ind_peso_promedio',
    code: 'ANTROP-03',
    name: 'Peso Corporal Promedio y Mediana',
    description: 'Promedio y mediana de peso corporal en kilogramos de la población con registro válido de peso.',
    category: 'ANTROPOMETRIA',
    formula: 'SUM(pesoKg) / COUNT(colaboradores con peso válido)',
    unit: 'kg',
    numerator: 'Suma de pesos en kg de registros válidos',
    denominator: 'Total de colaboradores con peso registrado y dentro de rango biológico (30–250 kg)',
    requiredFields: ['pesoKg'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_estatura_promedio',
    code: 'ANTROP-04',
    name: 'Estatura Promedio y Mediana',
    description: 'Promedio y mediana de estatura en metros de la población con registro válido de estatura.',
    category: 'ANTROPOMETRIA',
    formula: 'SUM(estaturaMts) / COUNT(colaboradores con estatura válida)',
    unit: 'm',
    numerator: 'Suma de estaturas en metros de registros válidos',
    denominator: 'Total de colaboradores con estatura registrada y dentro de rango biológico (1.00–2.30 m)',
    requiredFields: ['estaturaMts'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_perimetro_cintura',
    code: 'ANTROP-05',
    name: 'Perímetro de Cintura Promedio',
    description: 'Promedio y mediana de perímetro de cintura en centímetros. Si no existe registro, reporta NO_DATA.',
    category: 'ANTROPOMETRIA',
    formula: 'SUM(perimetroCinturaCm) / COUNT(colaboradores con cintura válida)',
    unit: 'cm',
    numerator: 'Suma de perímetro de cintura en cm',
    denominator: 'Total de colaboradores con medición de cintura válida',
    requiredFields: ['perimetroCinturaCm'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },

  // =========================================================================
  // 2. SOCIODEMOGRÁFICO
  // =========================================================================
  {
    id: 'ind_edad_promedio',
    code: 'DEMO-01',
    name: 'Edad Promedio de la Población',
    description: 'Promedio de edad calculada a partir de fecha de nacimiento válida (o edad directa verificada). Si no existe fecha válida -> NO_CALCULABLE.',
    category: 'SOCIODEMOGRAFICO',
    formula: 'SUM(YEAR(NOW) - YEAR(fechaNacimiento)) / COUNT(colaboradores con fecha de nacimiento válida)',
    unit: 'años',
    numerator: 'Suma de edades válidas',
    denominator: 'Colaboradores con fecha de nacimiento válida (18 a 90 años)',
    requiredFields: ['fechaNacimiento'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_edad_grupos',
    code: 'DEMO-02',
    name: 'Distribución por Grupos de Edad',
    description: 'Distribución etaria según rangos parametrizados (<18, 18–24, 25–34, 35–44, 45–54, 55–64, 65+).',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores en grupo etario) / COUNT(colaboradores con edad válida) * 100',
    unit: '%',
    numerator: 'Conteo de colaboradores en cada grupo etario',
    denominator: 'Total de colaboradores con fecha de nacimiento o edad válida',
    requiredFields: ['fechaNacimiento'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_sexo_distribucion',
    code: 'DEMO-03',
    name: 'Distribución por Sexo Biológico / Género',
    description: 'Distribución porcentual por sexo o identidad reportada.',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores por sexo) / COUNT(colaboradores con sexo válido) * 100',
    unit: '%',
    numerator: 'Conteo de colaboradores por categoría de sexo',
    denominator: 'Total de colaboradores con información válida de sexo',
    requiredFields: ['sexo'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_estado_civil',
    code: 'DEMO-04',
    name: 'Distribución por Estado Civil',
    description: 'Distribución de la población trabajadora por estado civil. No incluye MISSING en categorías válidas; las ausencias se reportan como "No informado".',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores por estado civil) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por estado civil reportado',
    denominator: 'Total de colaboradores con respuesta válida en estado civil',
    requiredFields: ['estadoCivil'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_nivel_educativo',
    code: 'DEMO-05',
    name: 'Nivel Educativo / Escolaridad',
    description: 'Nivel máximo de escolaridad alcanzado. Únicamente categorías reales reportadas sin inventar categorías inexistentes.',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores por nivel escolar) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por nivel educativo',
    denominator: 'Total de colaboradores con escolaridad reportada',
    requiredFields: ['nivelEscolaridad'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_tipo_vivienda',
    code: 'DEMO-06',
    name: 'Condición y Tenencia de Vivienda',
    description: 'Distribución de tipo de vivienda (Propia, Arrendada, Familiar). Prohibido inferir nivel socioeconómico de este campo.',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores por tipo vivienda) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por tipo de vivienda',
    denominator: 'Total de colaboradores con respuesta válida en vivienda',
    requiredFields: ['tipoVivienda'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_estrato_socioeconomico',
    code: 'DEMO-07',
    name: 'Estrato Socioeconómico',
    description: 'Distribución de estrato residencial reportado (1 al 6).',
    category: 'SOCIODEMOGRAFICO',
    formula: 'COUNT(colaboradores por estrato) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por estrato',
    denominator: 'Total de colaboradores con estrato reportado',
    requiredFields: ['estrato'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_composicion_familiar',
    code: 'DEMO-08',
    name: 'Composición Familiar y Personas a Cargo',
    description: 'Promedio de personas a cargo e hijos por colaborador. 0 hijos es un dato válido (cero hijos), null es no informado.',
    category: 'SOCIODEMOGRAFICO',
    formula: 'SUM(numeroPersonasCargo) / COUNT(colaboradores con dato válido)',
    unit: 'personas',
    numerator: 'Suma de personas a cargo reportadas',
    denominator: 'Total de colaboradores con dato válido de personas a cargo',
    requiredFields: ['personasACargo'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },

  // =========================================================================
  // 3. SOCIOLABORAL & ORGANIZACIONAL
  // =========================================================================
  {
    id: 'ind_antiguedad_promedio',
    code: 'LABOR-01',
    name: 'Antigüedad Promedio en la Organización',
    description: 'Años promedio de vinculación laboral calculados a partir de fechaIngreso real.',
    category: 'SOCIOLABORAL',
    formula: 'SUM(DATEDIFF(NOW, fechaIngreso) / 365.25) / COUNT(colaboradores con fecha de ingreso válida)',
    unit: 'años',
    numerator: 'Suma de años de permanencia de colaboradores con fecha válida',
    denominator: 'Colaboradores con fecha de ingreso verificable',
    requiredFields: ['fechaIngreso'],
    aggregationType: 'AVERAGE',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_antiguedad_rangos',
    code: 'LABOR-02',
    name: 'Distribución de Antigüedad por Rangos',
    description: 'Distribución por tramos de antigüedad (<1 año, 1–3 años, 3–5 años, >5 años).',
    category: 'SOCIOLABORAL',
    formula: 'COUNT(colaboradores en rango antigüedad) / COUNT(colaboradores con antigüedad válida) * 100',
    unit: '%',
    numerator: 'Conteo por rango de antigüedad',
    denominator: 'Total con fecha de ingreso válida',
    requiredFields: ['fechaIngreso'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_tipo_contrato',
    code: 'ORG-01',
    name: 'Distribución por Tipo de Contrato',
    description: 'Distribución laboral por modalidad contractual. Prohibido asignar "Término indefinido" por defecto.',
    category: 'ORGANIZACIONAL',
    formula: 'COUNT(colaboradores por tipo contrato) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por tipo de contrato',
    denominator: 'Total con tipo de contrato reportado (sin valores inventados)',
    requiredFields: ['tipoContrato'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_distribucion_sede',
    code: 'ORG-02',
    name: 'Distribución Poblacional por Sede',
    description: 'Población distribuida por sedes reales de trabajo. Prohibido inventar sedes predeterminadas.',
    category: 'ORGANIZACIONAL',
    formula: 'COUNT(colaboradores por sede) / COUNT(registros con sede informada) * 100',
    unit: '%',
    numerator: 'Conteo por sede de trabajo',
    denominator: 'Colaboradores con sede asignada válida',
    requiredFields: ['sede'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_distribucion_area',
    code: 'ORG-03',
    name: 'Distribución Poblacional por Área / Departamento',
    description: 'Población por área o gerencia. Si no existe -> "No informado".',
    category: 'ORGANIZACIONAL',
    formula: 'COUNT(colaboradores por área) / COUNT(registros con área informada) * 100',
    unit: '%',
    numerator: 'Conteo por área funcional',
    denominator: 'Colaboradores con área asignada válida',
    requiredFields: ['area'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_distribucion_proyecto',
    code: 'ORG-04',
    name: 'Distribución Poblacional por Proyecto',
    description: 'Población por proyecto o centro de costo real.',
    category: 'ORGANIZACIONAL',
    formula: 'COUNT(colaboradores por proyecto) / COUNT(registros con proyecto informado) * 100',
    unit: '%',
    numerator: 'Conteo por proyecto',
    denominator: 'Colaboradores con proyecto asignado válido',
    requiredFields: ['proyecto'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_modalidad_trabajo',
    code: 'ORG-05',
    name: 'Distribución por Modalidad de Trabajo',
    description: 'Distribución de trabajo Presencial, Remoto o Híbrido.',
    category: 'ORGANIZACIONAL',
    formula: 'COUNT(colaboradores por modalidad) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por modalidad de trabajo',
    denominator: 'Colaboradores con modalidad reportada',
    requiredFields: ['modalidadTrabajo'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0'
  },

  // =========================================================================
  // 4. SALUD & SÍNTOMAS OSTEOMUSCULARES
  // =========================================================================
  {
    id: 'ind_percepcion_salud',
    code: 'SALUD-01',
    name: 'Percepción Global del Estado de Salud',
    description: 'Autopercepción de salud reportada (Excelente, Bueno, Regular, Malo).',
    category: 'SALUD',
    formula: 'COUNT(colaboradores por nivel percepción) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por opción de autopercepción',
    denominator: 'Total con respuesta válida en percepción de salud',
    requiredFields: ['percepcionSalud'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_molestias_osteomusculares',
    code: 'SALUD-02',
    name: 'Prevalencia de Molestias Osteomusculares Reportadas',
    description: 'Porcentaje de colaboradores que reportan molestias o dolor osteomuscular. Terminología estricta: "molestias reportadas" o "dolor reportado" (no diagnósticos).',
    category: 'SALUD',
    formula: 'COUNT(colaboradores que reportan dolor/molestia) / COUNT(respuestas válidas en cuestionario osteomuscular) * 100',
    unit: '%',
    numerator: 'Colaboradores con reporte afirmativo de síntomas osteomusculares',
    denominator: 'Total de colaboradores con cuestionario de síntomas osteomusculares diligenciado',
    requiredFields: ['dolorOsteomuscular'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { max: 15.0, label: 'Baja prevalencia de molestias' },
      yellow: { min: 15.1, max: 35.0, label: 'Prevalencia moderada de molestias' },
      red: { min: 35.1, label: 'Alta prevalencia de molestias reportadas' }
    }
  },
  {
    id: 'ind_dolor_zonas_corporales',
    code: 'SALUD-03',
    name: 'Distribución de Molestias por Zona Corporal',
    description: 'Distribución anatómica de molestias reportadas (Cuello, Espalda/Lumbar, Hombros, Muñecas/Manos, Miembros inferiores).',
    category: 'SALUD',
    formula: 'COUNT(reportes por zona) / COUNT(colaboradores que reportan molestias) * 100',
    unit: '%',
    numerator: 'Conteo de reportes por segmento corporal afectado',
    denominator: 'Colaboradores que reportaron presencia de molestias osteomusculares',
    requiredFields: ['dolorZonas'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_consumo_medicamentos',
    code: 'SALUD-04',
    name: 'Uso de Medicamentos Permanentes Formulados',
    description: 'Proporción de colaboradores que consumen medicamentos de prescripción permanente (datos agregados, jamás exponer nombre + medicamento).',
    category: 'SALUD',
    formula: 'COUNT(colaboradores con medicamentos) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Colaboradores que reportan consumo de medicamentos permanentes',
    denominator: 'Colaboradores con respuesta válida en la pregunta de medicamentos',
    requiredFields: ['medicamentosPermanentes'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_alergias_conocidas',
    code: 'SALUD-05',
    name: 'Prevalencia de Alergias Conocidas',
    description: 'Proporción de colaboradores con reporte de alergias medicamentosas, ambientales o alimentarias.',
    category: 'SALUD',
    formula: 'COUNT(colaboradores con alergias) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Colaboradores con reporte de alergias',
    denominator: 'Colaboradores con respuesta válida en alergias',
    requiredFields: ['alergias'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_discapacidad_reportada',
    code: 'SALUD-06',
    name: 'Condición de Discapacidad Reportada',
    description: 'Proporción de personas con condición de discapacidad certificada o informada.',
    category: 'SALUD',
    formula: 'COUNT(colaboradores con discapacidad) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Colaboradores con reporte afirmativo de discapacidad',
    denominator: 'Colaboradores con respuesta válida',
    requiredFields: ['discapacidad'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 75,
    status: 'ACTIVE',
    version: '1.0.0'
  },

  // =========================================================================
  // 5. ESTILOS DE VIDA & HÁBITOS
  // =========================================================================
  {
    id: 'ind_actividad_fisica_regular',
    code: 'HABIT-01',
    name: 'Nivel de Actividad Física Regular',
    description: 'Porcentaje de colaboradores que realizan actividad física regular. "No respondió" NO equivale a "No realiza actividad".',
    category: 'ESTILO_VIDA',
    formula: 'COUNT(colaboradores que realizan actividad física) / COUNT(respuestas válidas en actividad física) * 100',
    unit: '%',
    numerator: 'Colaboradores que reportan practicar actividad física',
    denominator: 'Total de colaboradores que respondieron válidamente a la pregunta de actividad física',
    requiredFields: ['actividadFisica'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { min: 50.0, label: 'Buen nivel de actividad física' },
      yellow: { min: 30.0, max: 49.9, label: 'Nivel moderado de sedentarismo' },
      red: { max: 29.9, label: 'Alto sedentarismo' }
    }
  },
  {
    id: 'ind_participacion_actividades',
    code: 'HABIT-02',
    name: 'Frecuencia de Participación en Programas de Bienestar',
    description: 'Distribución por frecuencia (Frecuente, Ocasional, Rara vez, Nunca, No informado).',
    category: 'ESTILO_VIDA',
    formula: 'COUNT(colaboradores por frecuencia) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Conteo por nivel de participación',
    denominator: 'Total con respuesta válida en participación',
    requiredFields: ['participacionActividades'],
    aggregationType: 'DISTRIBUTION',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_tenencia_mascotas',
    code: 'HABIT-03',
    name: 'Tenencia de Animales de Compañía (Mascotas)',
    description: 'Proporción de colaboradores con mascotas (Sí, No, No informado). No inferir bienestar psicológico a partir de este indicador.',
    category: 'ESTILO_VIDA',
    formula: 'COUNT(colaboradores con mascotas) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Colaboradores que confirman tenencia de animales de compañía',
    denominator: 'Total de colaboradores con respuesta válida en tenencia de mascotas',
    requiredFields: ['mascotas'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0'
  },
  {
    id: 'ind_consumo_tabaco',
    code: 'HABIT-04',
    name: 'Prevalencia de Consumo de Tabaco / Cigarrillo',
    description: 'Porcentaje de fumadores habituales u ocasionales sobre respuestas válidas.',
    category: 'ESTILO_VIDA',
    formula: 'COUNT(fumadores activos) / COUNT(respuestas válidas) * 100',
    unit: '%',
    numerator: 'Colaboradores con consumo activo de tabaco',
    denominator: 'Total con respuesta válida en consumo de tabaco',
    requiredFields: ['fuma'],
    aggregationType: 'PERCENTAGE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { max: 10.0, label: 'Bajo consumo de tabaco' },
      yellow: { min: 10.1, max: 20.0, label: 'Consumo moderado' },
      red: { min: 20.1, label: 'Alto consumo de tabaco' }
    }
  },

  // =========================================================================
  // 6. AUSENTISMO & BIENESTAR
  // =========================================================================
  {
    id: 'ind_tasa_ausentismo',
    code: 'SST-01',
    name: 'Tasa de Ausentismo por Incapacidades Médicas',
    description: 'Porcentaje de días laborables perdidos por incapacidades médicas. Solo se calcula si existe fuente de incapacidades reales cargada; si no -> status = NO_DATA (cero estimaciones).',
    category: 'BIENESTAR_AUSENTISMO',
    formula: 'SUM(diasIncapacidad) / (TotalColaboradores * 240 diasProgramados) * 100',
    unit: '%',
    numerator: 'Total de días de incapacidad médica registrados en la fuente de ausentismo',
    denominator: 'Días-hombre programados en el periodo evaluado',
    requiredFields: ['diasIncapacidad'],
    aggregationType: 'RATE',
    minimumCoverage: 80,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { max: 3.0, label: 'Ausentismo bajo controlado' },
      yellow: { min: 3.1, max: 5.0, label: 'Ausentismo moderado' },
      red: { min: 5.1, label: 'Ausentismo crítico' }
    },
    notes: 'No inventa días de ausencia si la empresa no tiene módulo de ausentismo cargado.'
  },
  {
    id: 'ind_indice_bienestar',
    code: 'SST-02',
    name: 'Índice de Bienestar y Clima Laboral',
    description: 'Puntaje de bienestar evaluado mediante instrumento psicométrico o encuesta de clima estandarizada. No se infiere de variables sociodemográficas; si falta instrumento -> status = NO_DATA.',
    category: 'BIENESTAR_AUSENTISMO',
    formula: 'SUM(puntajeBienestar) / COUNT(encuestas de bienestar válidas)',
    unit: 'puntos',
    numerator: 'Suma de puntajes de bienestar reportados en el instrumento',
    denominator: 'Total de colaboradores que completaron el instrumento de bienestar',
    requiredFields: ['puntajeBienestar'],
    aggregationType: 'SCORE',
    minimumCoverage: 70,
    status: 'ACTIVE',
    version: '1.0.0',
    thresholds: {
      green: { min: 75.0, label: 'Bienestar favorable' },
      yellow: { min: 60.0, max: 74.9, label: 'Bienestar regular' },
      red: { max: 59.9, label: 'Bienestar desfavorable' }
    }
  }
];
